### ISSUE TITLE
[Feature] `DioInspector` TODOs

### ISSUE THREAD

**Issue by AlexV525** [bytedance/flutter_ume#15]
## Features

- [x] Basic inspects feature. #16
- [x] Real-time update with completed responses. #16
- [x] Responses list paging. #16
- [x] Copy contents in responses that delivered texts/maps. #16
- [ ] Count display with dot.
- [ ] Deliver requests to the container when they're sent.
- [ ] Multiple `Dio` instances support.

## Issues

- [x] #28
- [x] #53
- [x] #67

**Comment by talisk** [comment]
> Count display with dot

@AlexV525 You can implement `PluggableWithStream` abstract class to support showing red dot.

There're some other suggestions about `DioInspector`

1. If the body is JSON, and `content-type` is JSON too, we can display the formatted JSON with interactive widget.
2. Export the Ruquest and Response in cURL and `.har` format.
3. Pin/Unpin a Request
4. Filter the Request by RegExp
5. Only show the path or absolute url

And here's the screenshot of UME which is ByteDance internal use only. The open source version of UME should use it as a reference for learning.

![20211129-154223](https://user-images.githubusercontent.com/7621572/143827290-af18cee7-4198-4478-becc-f1227af04e9f.jpeg)

**Comment by hai046** [comment]
我看master已经有request header了，能否更新一下pub？

I see that the master already has `request header` info , can you update the pub?
